#!/usr/bin/lua
pa  = require("pulseaudio")

if (#arg) < 1 then
    os.exit(1)
end

headsets = {}
table.insert(headsets, "alsa_output.usb-Logitech_Logitech_Wireless_Headset_000D44D39CAA-00.analog-stereo")
for bt in string.gmatch(os.getenv("HEADSET_ADDRESS") or '', "(%S+)") do
    table.insert(headsets, "bluez_sink."..bt:gsub(':', '_')..".a2dp_sink")
end

sinks = {}
default_sink_name = nil
for i, sink in pairs(pa:get_sinks()) do
    if (tonumber(i) == nil) then
        sinks[i] = sink
        if (sink.default) then
            default_sink_name = sink.name
        end
    end
end

function sink_exists(sn)
    for name, _ in pairs(sinks) do
        if (sn == name) then
            return true
        end
    end
    return false
end

target = nil
for _, s in ipairs(headsets) do
    if sink_exists(s) then
        target = s
        break
    end
end
if (target == nil) then
    os.exit(0)
end

if (default_sink_name ~= target) then
    pa:set_default_sink(target)
    for _, input in pairs(pa:get_sink_inputs()) do
        pa:move_sink_input(input.index, sinks[target].index)
    end
else
    os.execute(table.concat(arg, ' '))
end
