#!/usr/bin/lua
pa = require("pulseaudio")

sink_names =
{
    headphones = "alsa_output.usb-Logitech_Logitech_Wireless_Headset_000D44D39CAA-00.analog-stereo",
    speakers   = "alsa_output.pci-0000_00_1f.3.analog-stereo",
    bluetooth  = "bluez_sink."..(os.getenv("HEADSET_ADDRESS") or ''):gsub(':', '_')..".a2dp_sink",
    ladspa     = "ladspa_sink",
    normalized = "ladspa_normalized_sink",
}

sinks = {}
default_sink_name = nil
for i, sink in pairs(pa:get_sinks()) do
    if (tonumber(i) == nil) then
        sinks[i] = sink
        if (sink.default) then
            default_sink_name = sink.name
        end
    end
end

function sink_exists(sn)
    for name, _ in pairs(sinks) do
        if (sn == name) then
            return true
        end
    end
    return false
end

function move(sn)
    if (sink_exists(sn) == true) then
        pa:set_default_sink(sn)
        for _, input in pairs(pa:get_sink_inputs()) do
            pa:move_sink_input(input.index, sinks[sn].index)
        end
    end
end

function move_to_speakers()
    move(sink_names.speakers)
    move(sink_names.ladspa)
    move(sink_names.normalized)
end

if (default_sink_name == sink_names.headphones) then
    if (sink_exists(sink_names.bluetooth)) then
        move(sink_names.bluetooth)
    else
        move_to_speakers()
    end
elseif (default_sink_name == sink_names.bluetooth) then
    move_to_speakers()
else
    if (sink_exists(sink_names.headphones)) then
        move(sink_names.headphones)
    elseif (sink_exists(sink_names.bluetooth)) then
        move(sink_names.bluetooth)
    end
end
